### ISSUE TITLE
Plugin says 51 emals. I did not send or receeive any. 

### ISSUE THREAD

**Issue by passdown1231** [awesomemotive/WP-Mail-SMTP#112]
## Expected Behavior

[](url) In plugin dashboard, all "emails" should be listed without pro subscription

## Current Behavior

Plugin lists 51 total emails despite the fact that none were sent from my account. Suggests some sort of hacking.

## Possible Solution

Provide a list of the 51 emails so I can figure out where they are coming from or going to. At this point, it's a security issue. Or plugin is corrupted.
![Screenshot 2022-03-23 at 13-25-35 Dashboard ‹ Write Your Life Story for Posterity — WordPress](https://user-images.githubusercontent.com/102253281/1https://passdownyourstory.com/wp-admin/index.php59773075-903a836e-e3ac-428a-becd-7db7e8440703.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by passdown1231** [comment]
My post above may not have been clear enough. To recap, the plugin counts a total of 51 emails but does not list them individually so I do not know anything about the emails. Since I did not send or receive emails, it seems imperative to look at them all and figure out why the plugin thinks there were 51. The phrasing suggests but does not state it is referring to incoming emails.

**Comment by capuderg** [comment]
Hi @passdown1231,

your screenshot is not working, I can't view it, but I think you are talking about the dashboard widget, right?
<img width="517" alt="Screenshot 2022-03-24 at 07 11 27" src="https://user-images.githubusercontent.com/9714134/159853571-4c91e534-bf64-4e5c-b847-e885702c6dfa.png">

The "Total" number means all the emails that your WP site sent since you activated our plugin. This is not a weekly or monthly number, it's a total number starting when you activated our WP Mail SMTP plugin.

This means your WP site sent out 51 emails since you activated our WP Mail SMTP plugin.

Take care!

**Comment by passdown1231** [comment]
Thanks for clarifying. But I did not send any emails and no one else has access to my site. That's why it's suspicious. Under the circumstances, reviewing the nature of the emails seems necessary

**Comment by capuderg** [comment]
WordPress will send out email for a lot of cases: password reset emails, critical error on the site, email changes, comments approval, ... If you have some other plugins installed, they can send some emails as well. If you have a contact form, that plugin will also send emails from your site...

There are a lot of cases that can send an email from your WP site :)

If you want to get future email logs (to verify what emails were sent out), we offer Email Logs in the Pro version, or you can install some other email logging plugin, but we can't guarantee its functionality/accuracy.

**Comment by passdown1231** [comment]
Thanks for explaining.
