### ISSUE TITLE
WP Mail SMTP

### ISSUE THREAD

**Issue by passdown1231** [awesomemotive/WP-Mail-SMTP#113]
## Expected Behavior

Update to previous post on this topic a week or so ago with new information regarding emails the plugin is reporting.

## Current Behavior
Got weekly status email from WP Mail SMTP saying: "Hi there, Let’s see how your emails performed in the past week. Total 58."
As I said last week, no one has sent emails from my website.  This weekly status report strongly implies the number is somehow due to my efforts. I am still seeking a rational explanation but increasingly concerned. 

		

Total Emails					 					 						58					 					 						 						 							 							+26.1% | Total Emails					 					 						58					 					 						 						 							 							+26.1% | Last week					 					 						0					 					 						 						 							 							-100% | Last week					 					 						0					 					 						 						 							 							-100%
-- | -- | -- | --
Total Emails					 					 						58					 					 						 						 							 							+26.1%
Last week					 					 						0					 					 						 						 							 							-100%

		<div style="line-height:40px;min-height:40px;" class="yiv9466416410spacer-40"> </div>
</body>
</html>

## Steps to Reproduce

1.
2.
3.
4.

**Comment by capuderg** [comment]
Hi @passdown1231,

in the lite version of our plugin, the weekly status email also refers to the total emails sent from your site. The "Total Emails" box will let you know how many emails were sent from your site in total (since you activated our plugin). And the "Last week" box will let you know how many emails were sent from your site last week.

From your provided info, last week, your site didn't send out any emails.

Take care!
