### ISSUE TITLE
Settings page has no authorise button

### ISSUE THREAD

**Issue by anitagraham** [awesomemotive/wp-mail-smtp#153]
## Plugin version 
1.2.5

## Current Behavior

I have set up the Gmail/Oauth settings to the point where the doc says I need to authorize the plugin to use the gmail account.  On my screen there is nothing further on the page.

I have logged out/in to the site.  I have checked the gmail id/secret.  I can't change them anyway as there is no submit/update button on the page.

I can switch to the Test Email Tab, which, after pressing send, comes back with a blank screen. I do not receive the email.

I have deactivated some security plugins which may have been causing a problem. In particular I had been using the Ithemes Security option to change backend slug, and wondered if this caused a problem with the callback url.  (Deactivated, no change).

I also deleted the wp-mail-smtp plugin, and downloaded it again. No change - and it has picked up the previous values. 

## Expected Behavior

* Settings page has a authorise/submit/update button. 
* Test email returns to a wp-admin page
* Test email sent/received

## Screenshots (if appropriate)

![wp-mail-smtp](https://user-images.githubusercontent.com/397118/36190922-b542d6d2-1195-11e8-9a40-6bf4b41a7dad.png)

**Thanks, Anita**

**Comment by slaFFik** [comment]
@anitagraham Thanks for the screenshot and the description, it was helpful.

Please take a look at your PHP error log and/or enable `WP_Debug`, as I'm sure there is something there related to WP Mail SMTP.
Here is a guide how to do that: http://www.wpbeginner.com/wp-tutorials/how-to-set-up-wordpress-error-logs-in-wp-config/

After doing that, please attach the zip file of that `debug.log` to this issue, I will review.

**Comment by slaFFik** [comment]
@anitagraham, any update on this issue?

**Comment by tttkhs** [comment]
I also encountered quite similar issue. I know current setting of wp mail SMTP is wrong but I can't change the setting due to same behavior ( there is no submit/update button on the page). 

version of WP Mail SMTP: 1.2.5 

====Debug log
[11-Mar-2018 06:06:43 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: Redirec
t URI must be absolute in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail
-smtp/vendor/google/auth/src/OAuth2.php:742
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/vendor/google/aut
h/src/OAuth2.php(335): Google\Auth\OAuth2->setRedirectUri('/wp-admin/optio...')
#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/vendor/google/api
client/src/Google/Client.php(942): Google\Auth\OAuth2->__construct(Array)
#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/vendor/google/api
client/src/Google/Client.php(922): Google_Client->createOAuth2Service()
#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/vendor/google/api
client/src/Google/Client.php(338): Google_Client->getOAuth2Service()
#4 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/src/Providers/Gma
il/Auth.php(293): Google_Client->createAuthUrl()
#5 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp in /opt/bitnami/apps/wordpr
ess/htdocs/wp-content/plugins/wp-mail-smtp/vendor/google/auth/src/OAuth2.php on line 74
2

**Comment by slaFFik** [comment]
Closing an initial issue by @anitagraham, because of the lack of communication.

@tttkhs, that's the issue with the install.
From the source code:
```php
            // "postmessage" is a reserved URI string in Google-land
            // @see https://developers.google.com/identity/sign-in/web/server-side-flow
            if ('postmessage' !== (string)$uri) {
                throw new InvalidArgumentException(
                    'Redirect URI must be absolute');
            }
```
So you need to investigate, what is the generate redirect URI, that's your local site URI.
