### ISSUE TITLE
More transparency on owner change and plans moving forward

### ISSUE THREAD

**Issue by hjoelr** [awesomemotive/wp-mail-smtp#42]
I just updated from WP-Mail-SMTP 0.10.1 to the 0.11.1 on one of my sites. It wasn't until I scanned through the code changes between the two that I noticed that the author had changed. I was a little disappointed that this was not clearly mentioned in the changelog of the extension. It's not that I have a problem with the ownership change, just that it wasn't clearly delineated.

I also noticed that there is now the ability for Awesome Motive to broadcast notifications to any admin of a site with this extension installed (see #11). That was not included in the changelog either. That seems like a significant enough thing to include there.

Anyway, since this is now owned by Awesome Motive, I was wondering what sort of plans are in order for this extension? Is it going to remain opensource?

**Comment by jaredatch** [comment]
Hey @hjoelr ,

Thanks for reaching out!

I apologize, I'm the one who approved the changelog and I agree that mentioning the ownership change certainly wouldn't have been a bad idea. I was just excited to get version `0.11` out the door and available to our 700k users. 😁

It slipped my mind since the the actual switch was over the summer, so it wasn't a recent event. After ownership transfer we did update the information in the actual WordPress.org repo as well as here on GH.

Things are in good hands though, I can ensure you that. At Awesome Motive have a _long_ history with WordPress and are deeply committed to our plugins.

We absolutely have many exciting things planned for the future of WP Mail SMTP. Callum did a solid job with things, but we're is in the process of a much needed refactor that will not only greatly improved the plugin, but also include new features. As a PHP developer, with future release you'll be able to extend the plugin to easily add support for new email providers (eg Amazon SES) - on top of the providers we're going to support in core! You can browser the `develop` branch to see some of thing things we have up our sleeves - @slaFFik have been hard at work and really committed to making the version `1.0` release awesome.

The notification functionality is so that we can inform users about the `1.0` release before it's arrival. The new release will contain an Admin UI overhaul (much improved) along with proper branding (we have a cool Pigeon mascot now ... get it... carrier pigeon... 😆). We've learned with an update of this magnitude, even though it's all for the better, to provider users with a "heads up" ahead of release. This helps minimize the confusion when they upgrade.

Lastly, we absolutely plan to keep the plugin 100% open source (and here on GH). With 700k+ installs it's already the most popular SMTP plugin in the WP.org repo and our long term plans are to make it even better and more user friendly. With our sister plugin, WPForms, we see first hand just how confusing and important email deliverability is for users.

Hope that helps. If you have any other questions just let me know!

**Comment by hjoelr** [comment]
@jaredatch Thanks for the fast and thorough reply. That does help set my mind at ease. Are you considering releasing a new minor version where you mention these things in the changelog? I'm sure there are a large number of people who have not installed the update yet and there would still be benefit to having it in the changelog.

**Comment by jaredatch** [comment]
I'm not going to push a new release for changelog updates, but I'll try to update the changelog whenever we have another minor release (bug fixes or whatever).

Cheers!

**Comment by hjoelr** [comment]
@jaredatch Okay, that sounds good. Thanks for 'dialoging' about this stuff.
