### ISSUE TITLE
Make password field input of the type "password"

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#49]
Not more secure, but at least makes some users a bit more happy and sort of a protection from over-the-shoulder observers.

**Comment by F3L1X79** [comment]
Woot, finally!
I personally use your plugin and had to modify this line each update to make the field of password-type.
I also think it's a bit better because it protects a bit for non-developer to access the password too easily. 

By the way, may I ask why you cannot use an encryptor/decryptor library like [RNCryptor](https://github.com/RNCryptor/RNCryptor-php) to store the password in database?

**Comment by slaFFik** [comment]
Microsoft advises to Disable its own "Store password using reversible encryption" feature [here](https://docs.microsoft.com/en-us/windows/device-security/security-policy-settings/store-passwords-using-reversible-encryption).

In short - it complicates the hacker life just a bit. Most of the sites are still not using SSL, so those passwords are sent in plaintext anyway.

I would still use a `WPMS_SMTP_PASS` constant in `wp-config.php`. Then, if the password is stored that way - it won't even be displayed in the admin area, as of 1.0.
