### ISSUE TITLE
Reconsider Migration.php logic

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#57]
## Current Behavior

It generates errors when upgrading from 0.11 to 1.0.
It was ok in October, so something is changed since then.

## Expected Behavior

Migration should be automatic and should resave options to a new format, deleting the old values.
@jaredatch Do you agree with the old options deletion?

## Steps to Reproduce (for bugs)

1. Install and configure 0.11 (SMTP options)
2. "Update" to 1.0 by putting files on  top (with deletion of old ones, like WP does it on plugin update)
3. Check that there are not errors in logs, on a site
4. Check that data is migrated successfully and emails are sending

**Comment by jaredatch** [comment]
I think we should delete the old options, but wait until a future release in Q1 2018.

The reason is because any issues or friction that may pop up from the `1.0` upgrade (regardless if our fault, user, web host, email provider, etc)... one of the first steps users will take to resolve the issue is downgrading back t`o 0.11.x`.

We don't want to (yet) kill user's ability to downgrade.
