### ISSUE TITLE
authorization leads to 403 forbidden

### ISSUE THREAD

**Issue by TamarCohen** [awesomemotive/WP-Mail-SMTP#64]
## Plugin version 
גרסה 1.8.1

## Current Behavior

[https://www.cps.co.il/wp-content/uploads/2020/03/403forbidden.jpg](url)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by slaFFik** [comment]
This can be due to security prevention from your hosting company. Most probably, `mod_security` apache module, it filters out certain requests and redirects them to a 404 or 403 page. You will need to contact your hosting company support team and ask to modify the `mod_security` rule to allow incoming requests from Google that have an URL in one of the GET params.
