### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by abronton** [awesomemotive/WP-Mail-SMTP#72]
I installed and activated WP Mail SMTP from within my WP site and it immediately gave me a "There has been a critical error on your website. Please check your site admin email inbox for instructions."  I'd like to go to my site admin email but the listed email doesn't exist.

No matter what I click on in the admin center nothing changes.  How do I remove the plugin and rescue my site?

**Comment by capuderg** [comment]
Hi @abronton,

I'm sorry you had a bad experience with our plugin.

It's very likely that your WP site failed to create the database tables needed for the plugin to work properly. Since your WP dashboard is inaccessible, please follow [these steps](https://wordpress.org/support/topic/there-has-been-a-critical-error-on-your-website-45/page/2/#post-12961434) to potentially resolve your issues.

The first step in the above link is to disable our plugin. You can do that by these instructions below:

You can rename the plugin folder "wp-mail-smtp" to something else, for example: "old-wp-mail-smtp".

Here is a [guide](https://www.wpbeginner.com/beginners-guide/how-to-easily-deactivate-wordpress-plugins/#deactivateallpluginsviaftp) describing how to deactivate all plugins, but you should go into the "plugins" folder and find "wp-mail-smtp" and rename it. That will deactivate only this plugin.

Let me know how it goes.

Take care!
