### ISSUE TITLE
Trying to get server's hostname using '$_SERVER['SERVER_NAME']'

### ISSUE THREAD

**Issue by sigismund** [awesomemotive/WP-Mail-SMTP#78]
## Expected Behavior
Wordpress emails may be sent using PHP-CLI which doesn't have $_SERVER['SERVER_NAME'] defined.

## Current Behavior
Warning (`Undefined index: SERVER_NAME`) is triggered when calling method WPMailSMTP\WP::get_default_email().

## Possible Solution
You could try switching to gethostname(); which is available in all supported PHP versions.

**Comment by capuderg** [comment]
Hi Žiga,

we are using the exact code WP core is using for getting the default WP email address: [wp core code](https://github.com/WordPress/WordPress/blob/master/wp-includes/pluggable.php#L333).

Does this PHP warning actually prevent you from sending emails? This should not cause a fatal error and should return `wordpress@` where called in our plugin (instead of `wordpress@example.com` if the server name is defined).

Take care!

**Comment by sigismund** [comment]
Hi Gregor :)

> we are using the exact code WP core is using for getting the default WP email address: [wp core code](https://github.com/WordPress/WordPress/blob/master/wp-includes/pluggable.php#L333).

This is not entirely true, if you look at [WP SMTP code](https://github.com/awesomemotive/WP-Mail-SMTP/blob/ddf20a5acb637a15a8661178f4dc9ccc5cf10380/src/WP.php#L253) you will see that it uses `$_SERVER` while WP Core uses home url as "source".


It's true that this doesn't prevent me from sending emails, but warnings are usually there for a reason ;)

**Comment by capuderg** [comment]
Hi,

hehe, they changed the code for WP 5.5 ([link](https://github.com/WordPress/WordPress/commit/d7453598b3950111af2ff12b01ef3cc007c5a009))... They used the "`$_SERVER`" code for a while now :)

We'll probably do the same in our plugin.

Thank you for reporting this issue!

Lep pozdrav! :)

**Comment by slaFFik** [comment]
This is fixed and will be released in the upcoming v2.3 of the plugin.
