### ISSUE TITLE
Not compatible with Wordpress 5.5

### ISSUE THREAD

**Issue by seanqc** [awesomemotive/WP-Mail-SMTP#80]
Currently unable to send any emails (including test emails). Issue appeared after upgrading to WordPress 5.5, with wp_debug enabled the following messages appears:

Deprecated: class-phpmailer.php is deprecated since version 5.5.0! Use wp-includes/PHPMailer/PHPMailer.php instead. The PHPMailer class has been moved to wp-includes/PHPMailer subdirectory and now uses the PHPMailer\PHPMailer namespace. in /home/xxxxxxxxxxxx/domains/xxxxxxxxxxxxx.com/public_html/wp-includes/functions.php on line 4963

**Comment by capuderg** [comment]
Hi @seanqc,

which version of our plugin are you using?

The current/latest version of our plugin 2.2.1 already has support for WP 5.5 and should not be causing this Deprecated notice.

If you are on the v2.2.1 then I think some other plugin is requiring the old version of PHPMailer class.

Please search your server for "PHPMailer" in the `.php` files and check which plugin/theme is requiring the old version of the WP core PHPMailer class. If you find it, try to disable that plugin and see if that will resolve your issue.

Otherwise, please go to WP Mail SMTP -> Settings -> Email Test (tab) and send an email test. If there is an error, please click on the link to expand the debug log at the bottom of the page and copy/paste the debug log here.

Let me know how it goes.

**Comment by seanqc** [comment]
Wow I'm so sorry I didn't check if I had the latest version of your plugin... I just updated and everything is working for fine. Sorry about that and keep up the great work!
