### ISSUE TITLE
Apparent issue with Gmail connector

### ISSUE THREAD

**Issue by thegadflyuk** [awesomemotive/WP-Mail-SMTP#81]
## Expected Behavior
I have connected our G Suite account, and test e-mails send successfully. On that basis I would expect system e-mails to send successfully too.

## Current Behavior
Apparently a system e-mail was supposed to have been sent, and wasn't. I got the following notification from WP Mail SMTP:

`EMAIL DELIVERY ERROR: the plugin WP Mail SMTP v2.3.1 logged this error during the last time it tried to send an email:`
`Mailer: Gmail`
`This function no longer exists. See UPGRADING.md for more information`
`Consider running an email test after fixing it.`

A further e-mail test ran fine.

## Steps to Reproduce
I'm not certain what e-mail the system was trying to send, so I can't reproduce it. It could not have come from a user interaction, the site is currently being staged for launch on 1 September; I am currently the only one with access.

**Comment by capuderg** [comment]
Hi @thegadflyuk,

the first thing that comes to mind would be, that another plugin is loading a different version of the Google API library: `google/apiclient`. Since that plugin (or a theme) is loading an older version of the Google API library and is loading it first, our plugin does not have any chance, but to use this loaded library.

Could you please tell us some basic WP site information? PHP version, WP version, a list of all active plugins, the theme that you are using?

You could also make a search on your server for `vendor/google/apiclient/src/Google/Client.php` or just for the `Google` folder.

Take care!

**Comment by malwarebo** [comment]
I have the same issue. This is specific to when you try to send emails using the Gmail mailer service in the plugin. No other plugin on my sites is using Google API client. 

`PHP Fatal error:  Uncaught Error: Undefined class constant 'VERSION' in /var/app/current/web/app/plugins/wp-mail-smtp/vendor/google/apiclient/src/Google/Client.php:1109\nStack trace:\n#0 /var/app/current/web/app/plugins/wp-mail-smtp/vendor/google/apiclient/src/Google/Client.php(1087): Google_Client->createDefaultHttpClient()\n#1 /var/app/current/web/app/plugins/wp-mail-smtp/vendor/google/apiclient/src/Google/Client.php(281): Google_Client->getHttpClient()\n#2  `

The new Google API client library seems to have fixed this issue. [Google API Client issue](https://github.com/googleapis/google-api-php-client/issues/1915)

**Comment by capuderg** [comment]
Hi @malwarebo,

your PHP error is connected with the Guzzle library. The line 1109 in `google/apiclient/src/Google/Client.php` is trying to get the guzzle's `VERSION` constant, but it can't find it.

I think some other plugin is loading the latest version of Guzzle library 7.x (which only supports PHP version 7.2+) and since we also support PHP 5.5 we can't update to the latest version of Guzzle. We are using the latest Guzzle 6.x version (6.5.5), which still supports PHP 5.5.

You can find which plugin/theme is using the guzzle library and if it's not an essential plugin you can deactivate it and our plugin should start working OK.

We are working on resolving these vendor conflicts and the fix should be available in the next plugin update, but I don't have an exact time/date when that will be.

Take care!

**Comment by malwarebo** [comment]
Hey @capuderg , yes there was a plugin using the Guzzle library. I deleted the plugin, and I am still seeing this issue. I don't think there is any other plugin using the Guzzle library. Thanks looking forward to the fix!

**Comment by capuderg** [comment]
Hi @malwarebo,

please make sure there aren't some other plugins that are using Guzzle as well. You can just temporarily disable them, to test if our plugin starts to work again.

Which plugin did you remove so far? Was it using the latest Guzzle version 7.x?

If you have any caching plugins, please clear all cache before performing the test again.

Take care!
