### ISSUE TITLE
send email as plane text toggle

### ISSUE THREAD

**Issue by donaca4555** [awesomemotive/WP-Mail-SMTP#86]
## Expected Behavior
send email as plane text toggle on the main settings page

**Comment by slaFFik** [comment]
Unfortunately, we won't implement this option.

Various plugins do not provide plain text part of the email. So forcing them to send the content of the email from HTML to plain text will require parsing the original HTML email and preparing a plain text version of it. That's a very complicated task because of the wide variety of plugins and their email designs - it's hard to always correctly preserve links, images, advanced markup, and extract a meaningful text without losing anything important.

It's **much** easier to create an HTML email out of the plain text, though.
