### ISSUE TITLE
WP Mail SMTP Wordpress Plugin fatal error brought website down.

### ISSUE THREAD

**Issue by bhedstrom** [awesomemotive/WP-Mail-SMTP#88]
We had to disable the plugin to get the site back up.

The reported error is:
Fatal error: require_once(): Failed opening required '/www/wp-content/plugins/wp-mail-smtp/wp-mail-smtp.php' (include_path='.:/usr/share/php') in /www/wp-content/plugins/wp-mail-smtp/wp_mail_smtp.php on line 229

Plugin Version 2.5.1

**Comment by capuderg** [comment]
Hi @bhedstrom,

did this happen after the plugin just updated to the latest version?

I've downloaded the plugin zip from here: https://wordpress.org/plugins/wp-mail-smtp/ and the file: `wp-mail-smtp/wp-mail-smtp.php` is present... I'm not sure how this error could occur since the file is clearly in the plugin zip file.

Could you please try to manually update the plugin with a new zip file from the above URL?

I think the WP plugin update had some issues and maybe did not extract all files properly.

Let me know how it goes.

Take care!

**Comment by slaFFik** [comment]
Due to the lack of activity, I'm closing this issue.
