### ISSUE TITLE
Conflict with Monsterinsights plugin

### ISSUE THREAD

**Issue by buggles333** [awesomemotive/WP-Mail-SMTP#9]
Following on from this question from the WP support forum - https://wordpress.org/support/topic/conflict-with-analytics-plugin-and-api/

Do you have a date for 1.3.0 release, or a fix in the meantime?

**Comment by slaFFik** [comment]
There is no conflict with MI, as MI doesn't include Google library at all. And I was unable to replicate the issue with GADWP.

Although `Simple GA Ranking` definitely breaks the WP Mail SMTP. I will see what can be done easily, but because that plugin has a small user base I won't make plugin-specific tweaks and will try to appy a general fix that should fit every other plugin. It's already in the work.
