### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by mwoodpatrick** [awesomemotive/WP-Mail-SMTP#95]
![auth_issue](https://user-images.githubusercontent.com/2222402/128629979-b2d248a8-456b-439f-ba25-1a6012c0853e.jpg)
## Expected Behavior
I installed version  3.0.2 and was re-enabling the connection 

## Current Behavior
Google gave me the error

Authorization Error
Error 400: redirect_uri_mismatch
You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy. \n\nIf you're the app developer, register the redirect URI in the Google Cloud Console.
Learn more
Request Details
redirect_uri=https://connect.wpmailsmtp.com/google/

How to fix

**Comment by capuderg** [comment]
Hi @mwoodpatrick 

it looks like your Google's OAuth app does not have the correct Redirect URI configured. 

Please add the `https://connect.wpmailsmtp.com/google/` URL to your Google's OAuth app Redirect URI setting. You can also [follow the steps in this guide](https://wpmailsmtp.com/docs/how-to-set-up-the-gmail-mailer-in-wp-mail-smtp/), in order to see where this URL has to be added.

Once you do that, please perform the connection in our plugin settings. That will resolve your issue.

I'll close this issue, but if you still have any problems, please let us know and we'll reopen it.

Take care!
