### ISSUE TITLE
PHP Issues

### ISSUE THREAD

**Issue by leojrpan** [awesomemotive/WP-Mail-SMTP#99]
[WPMAIL 2.txt](https://github.com/awesomemotive/WP-Mail-SMTP/files/6994226/WPMAIL.2.txt)
[WPMAIL 3.txt](https://github.com/awesomemotive/WP-Mail-SMTP/files/6994227/WPMAIL.3.txt)
[WPMAIL 4.txt](https://github.com/awesomemotive/WP-Mail-SMTP/files/6994228/WPMAIL.4.txt)
[WPMAIL 5.txt](https://github.com/awesomemotive/WP-Mail-SMTP/files/6994229/WPMAIL.5.txt)
[WPMAIL.txt](https://github.com/awesomemotive/WP-Mail-SMTP/files/6994230/WPMAIL.txt)

Hi there,

I was about to upgrade my website to PHP 7.4 but I had some alerts regarding some plugins including WP Mail SMTP. I am attaching files that specify what those errors are. I am trying to avoid crashing the site or losing functionality while upgrading.

I currently am on plugin version 3.0.3

Thank you.

**Comment by capuderg** [comment]
Hi @leojrpan,

these errors are all located in the `vendor_prefixed` folder of our plugin. This is where the 3rd party libraries are stored and we don't have immediate access to fix these issues, because they are maintained by a 3rd party company. Some of these errors are only in the files that serve as backwards compatibility or they are never used/executed by our plugin.

We are using PHP 7.4 every day and we don't have any issues with our plugin, so you should be just fine updating to PHP 7.4.

Thank you for reporting these errors and let me know if you have any other questions.

Take care!
